# Generated by Django 5.0.6 on 2024-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='IsFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
