# Generated by Django 5.0.6 on 2024-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_isfeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
