# Generated by Django 5.0.6 on 2024-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_published_date_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
